global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

# define which exporters to scrape
scrape_configs:
  - job_name: varnish
    # 'exporter' is our exporter container in `docker-compose.yml`
    # metrics_path defaults to '/metrics', scheme to 'http'
    static_configs:
      - targets: ["exporter:9131"]
